#=================================================
# The SCONSTRUCT file for building HIPO project.
# 
#=================================================
import glob
import os
import sys
#=================================================
# LOADING THE ENVIRONMENT
#=================================================
env = Environment(CPPPATH=["include",".","/usr/include","/usr/local/include","/opt/local/include","/group/clas12/packages/lz4/lib","/group/clas12/packages/hipo-io/libcpp","/site/12gev_phys/2.2/Linux_CentOS7.2.1511-x86_64-gcc4.8.5/root/6.12.06/lib","/site/12gev_phys/2.2/Linux_CentOS7.2.1511-x86_64-gcc4.8.5/root/6.12.06/include"])
env.Append(ENV = os.environ)
env.Append(CPPPATH=["src/root","src/evio"])
env.Append(CCFLAGS=['-std=c++11','`root-config --libs`',"-O2","-fPIC","-m64","-fmessage-length=0","-g"])
env.Append(LIBPATH=["/opt/local/lib","/usr/lib","/usr/local/lib","/group/clas12/packages-old/lz4/lib","lib","/group/clas12/packages-old/hipo-io/lib", "/site/12gev_phys/2.2/Linux_CentOS7.2.1511-x86_64-gcc4.8.5/root/6.12.06/lib"])
env.Append(CONFIGUREDIR=["/group/clas12/packages-old/lz4/lib","/group/clas12/packages-old/hipo-io/lib"])
#=================================================
# Check for compression libraries.
#=================================================
conf = Configure(env)

if conf.CheckLib('libhipo'):
   print '\n\033[32m[**] >>>>> found library : HIPO'
   print ''
   env.Append(CCFLAGS="-D__HIPO__")
    
if conf.CheckLib('liblz4'):
   print '\n\033[32m[**] >>>>> found library : LZ4'
   print '[**] >>>>> enabling lz4 compression. \033[0m'
   print ''
   env.Append(CCFLAGS="-D__LZ4__")

if conf.CheckLib('libz'):
   print '\n\033[32m[**] >>>>> found library : libz'
   print '[**] >>>>> enabling gzip compression. \033[0m'
   print ''
   env.Append(CCFLAGS="-D__LIBZ__")
#=================================================
# BUILDING EXECUTABLE PROGRAM
#=================================================
runFileLoop   = env.Program(target="runFileLoop",source=["runFileLoop.cc"],LIBS=['Core','RIO','Net','Hist','Graf','Graf3d','Gpad','Tree','Rint','Postscript','Matrix','Physics','MathCore','Thread','MultiProc','m', 'dl','hipo','lz4'])
